import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/reset.css";
import Header from "@/components/header"
import Footer from "@/components/footer"

export const metadata: Metadata = {
  title: "ANKAROM",
  description: "Generated by create next app",
  icons: {
    icon: '/ankarom.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="container" suppressHydrationWarning={true}>
        <Header/>
        <main className="bg-white/5 backdrop-blur-md border border-white/10 rounded-[40px] p-12 text-gray-200 shadow-2xl">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
