import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/reset.css";
import Header from "@/components/header"
import Footer from "@/components/footer"
import { CartProvider } from "@/components/cart/CartProvider";
import { AuthProvider } from "@/components/auth/AuthProvider";

export const metadata: Metadata = {
  title: "ANKAROM",
  description: "Generated by create next app",
  icons: {
    icon: '/ankarom.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="container" suppressHydrationWarning={true}>
        <AuthProvider>
          <CartProvider>
            <Header/>
            <main className="text-gray-200">{children}</main>
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
